/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pillars: Pillar;
    authors: Author;
    tags: Tag;
    articles: Article;
    wireDrops: WireDrop;
    corrections: Correction;
    sponsorSlots: SponsorSlot;
    engineConflictLog: EngineConflictLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pillars: PillarsSelect<false> | PillarsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    wireDrops: WireDropsSelect<false> | WireDropsSelect<true>;
    corrections: CorrectionsSelect<false> | CorrectionsSelect<true>;
    sponsorSlots: SponsorSlotsSelect<false> | SponsorSlotsSelect<true>;
    engineConflictLog: EngineConflictLogSelect<false> | EngineConflictLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Author: draft/submit. Editor: publish + manage taxonomy. Admin: full access. 2FA enforced on Editor + Admin in production.
   */
  role: 'author' | 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Uploaded images. Stored in Cloudflare R2 in production.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text — required for accessibility (WCAG 2.1 AA).
   */
  alt: string;
  /**
   * Photographer / source credit, shown as the caption.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Top-level beats. Order controls nav + homepage band order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillars".
 */
export interface Pillar {
  id: number;
  /**
   * URL slug, matches frontend pillar ids (ai|startups|latest|dev|products|policy).
   */
  slug: string;
  /**
   * Short label for nav, chips, and homepage band (e.g. "AI").
   */
  title: {
    en: string;
    vi?: string | null;
    id?: string | null;
  };
  /**
   * Long heading shown as the H1 on the pillar page (e.g. "Artificial Intelligence"). Falls back to the short title if empty.
   */
  heading?: string | null;
  /**
   * CSS color reference (var(--ai) etc.) used in nav + cover art tints.
   */
  color: string;
  /**
   * Icon name from apps/web/src/components/icons.tsx (spark | trend-up | clock | code | product | policy).
   */
  icon: string;
  /**
   * Lower = earlier in nav + homepage Pillar Showcase.
   */
  order: number;
  /**
   * Short tagline shown on the pillar page header. One sentence.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Byline role: 'Asia Bureau Chief', 'AI Correspondent', etc.
   */
  role: string;
  /**
   * Reporter base. Used by the CityChip on the homepage Wire Drops and by the article header.
   */
  city: string;
  /**
   * Short author bio. Shown on the author page (future).
   */
  bio?: string | null;
  /**
   * Optional link to a CMS user. Lets us auto-fill the byline when the user publishes.
   */
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * URL slug, lowercase-dashed.
   */
  slug: string;
  title: {
    en: string;
    vi?: string | null;
    id?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Every story DTW publishes. Engine drafts flow in via API; editors review here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL slug. Auto-generated from title; editor can override.
   */
  slug: string;
  dek: string;
  /**
   * Article body. Stays in source language (translation invariant).
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  section?: string | null;
  readMin: number;
  publishedAt: string;
  /**
   * One pillar per article.
   */
  pillar: number | Pillar;
  tags?: (number | Tag)[] | null;
  /**
   * Primary byline.
   */
  author: number | Author;
  coAuthors?: (number | Author)[] | null;
  /**
   * Triggers the AI-assisted disclosure box at top + middle + bottom. Non-dismissible (invariant).
   */
  aiAssisted?: boolean | null;
  /**
   * Triggers the Paid Partner band + top/middle/bottom disclosures. Sponsor name required.
   */
  sponsored?: boolean | null;
  /**
   * Sponsor brand name (shown on the disclosure box).
   */
  sponsor?: string | null;
  affiliate?: boolean | null;
  deepDive?: boolean | null;
  /**
   * Pins this story to the top of the Latest feed (the /latest featured slot) and the homepage Latest band. Manual — untick to unpin. Newest wins if several are pinned.
   */
  pinnedToLatest?: boolean | null;
  /**
   * How this article entered the system.
   */
  origin: 'engine' | 'manual';
  /**
   * True if any CMS user has touched this article. Engine writes set false; editor writes set true.
   */
  editedByHuman?: boolean | null;
  /**
   * Field names the Engine must NEVER overwrite (e.g. title, dek, body). Locked fields persist until explicitly released.
   */
  lockedFields?:
    | {
        field?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optimistic-lock counter. Bumped on every write.
   */
  version: number;
  /**
   * Provenance: canonical URL of the source the Engine rewrote from. Set by the intake endpoint; read-only.
   */
  engineSourceUrl?: string | null;
  /**
   * Provenance: publisher/source name the Engine rewrote from. Set by the intake endpoint; read-only.
   */
  engineSourceName?: string | null;
  /**
   * Hero image (uploaded to R2). If empty, the reader falls back to generative cover art.
   */
  heroImage?: (number | null) | Media;
  /**
   * Label overlaid on the generative cover art when there is no hero image.
   */
  imageLabel?: string | null;
  /**
   * Deprecated — use the heroImage upload instead. External URL fallback only.
   */
  imageUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Realtime band on the homepage. Auto-published on insert. Keep each drop under 150 chars.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wireDrops".
 */
export interface WireDrop {
  id: number;
  /**
   * Display time string e.g. '08:42'. Local time, no timezone.
   */
  time: string;
  city: string;
  /**
   * ≤ 150 chars (the spec); we cap at 200 server-side as a safety net.
   */
  text: string;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Public corrections log. Every entry shows on /trust/corrections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corrections".
 */
export interface Correction {
  id: number;
  article: number | Article;
  correctionDate: string;
  /**
   * One-line summary that appears next to the article title.
   */
  summary: string;
  /**
   * The incorrect text, struck through in the log.
   */
  wasText: string;
  /**
   * The corrected text.
   */
  nowText: string;
  /**
   * User who signed off the correction.
   */
  editor?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sponsored placements config. One row per slot location.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsorSlots".
 */
export interface SponsorSlot {
  id: number;
  slot: 'homepage_strip' | 'dashboard_funding' | 'dashboard_ai';
  /**
   * The sponsored article to feature. Empty = the slot renders nothing.
   */
  article?: (number | null) | Article;
  startsAt?: string | null;
  endsAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Read-only audit. Populated automatically by the conflict detector (Phase E4).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engineConflictLog".
 */
export interface EngineConflictLog {
  id: number;
  article: number | Article;
  /**
   * Field name the Engine tried to write.
   */
  field: string;
  /**
   * What the Engine tried to write.
   */
  engineValue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * What was in the DB at the time.
   */
  currentValue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reason: 'locked' | 'human_edited' | 'version_mismatch';
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pillars';
        value: number | Pillar;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'wireDrops';
        value: number | WireDrop;
      } | null)
    | ({
        relationTo: 'corrections';
        value: number | Correction;
      } | null)
    | ({
        relationTo: 'sponsorSlots';
        value: number | SponsorSlot;
      } | null)
    | ({
        relationTo: 'engineConflictLog';
        value: number | EngineConflictLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillars_select".
 */
export interface PillarsSelect<T extends boolean = true> {
  slug?: T;
  title?:
    | T
    | {
        en?: T;
        vi?: T;
        id?: T;
      };
  heading?: T;
  color?: T;
  icon?: T;
  order?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  city?: T;
  bio?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  slug?: T;
  title?:
    | T
    | {
        en?: T;
        vi?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  dek?: T;
  body?: T;
  section?: T;
  readMin?: T;
  publishedAt?: T;
  pillar?: T;
  tags?: T;
  author?: T;
  coAuthors?: T;
  aiAssisted?: T;
  sponsored?: T;
  sponsor?: T;
  affiliate?: T;
  deepDive?: T;
  pinnedToLatest?: T;
  origin?: T;
  editedByHuman?: T;
  lockedFields?:
    | T
    | {
        field?: T;
        id?: T;
      };
  version?: T;
  engineSourceUrl?: T;
  engineSourceName?: T;
  heroImage?: T;
  imageLabel?: T;
  imageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wireDrops_select".
 */
export interface WireDropsSelect<T extends boolean = true> {
  time?: T;
  city?: T;
  text?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corrections_select".
 */
export interface CorrectionsSelect<T extends boolean = true> {
  article?: T;
  correctionDate?: T;
  summary?: T;
  wasText?: T;
  nowText?: T;
  editor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsorSlots_select".
 */
export interface SponsorSlotsSelect<T extends boolean = true> {
  slot?: T;
  article?: T;
  startsAt?: T;
  endsAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engineConflictLog_select".
 */
export interface EngineConflictLogSelect<T extends boolean = true> {
  article?: T;
  field?: T;
  engineValue?: T;
  currentValue?: T;
  reason?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}